/* ==========================================================================
   Tailwind CSS Configuration
   Must be defined before Tailwind's CDN script executes, so this file is
   loaded with the `id="tailwind-config"` attribute on its <script> tag.
   ========================================================================== */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container":       "#c4cfff",
        "surface-container-low":        "#181b25",
        "surface":                      "#0f131c",
        "on-tertiary":                  "#003919",
        "primary-fixed":                "#64ff92",
        "surface-container":            "#1c1f29",
        "on-tertiary-fixed-variant":    "#005227",
        "tertiary":                     "#95e2a5",
        "on-primary-container":         "#005324",
        "on-secondary-fixed-variant":   "#003cad",
        "on-error":                     "#690005",
        "surface-tint":                 "#30e375",
        "tertiary-fixed-dim":           "#8ad89b",
        "tertiary-fixed":               "#a6f4b6",
        "surface-container-lowest":     "#0a0e17",
        "error":                        "#ffb4ab",
        "secondary-fixed":              "#dce1ff",
        "on-primary-fixed-variant":     "#005224",
        "on-error-container":           "#ffdad6",
        "secondary":                    "#b5c4ff",
        "surface-container-highest":    "#31353f",
        "secondary-fixed-dim":          "#b5c4ff",
        "inverse-primary":              "#006d32",
        "inverse-on-surface":           "#2c303a",
        "surface-variant":              "#31353f",
        "on-tertiary-fixed":            "#00210c",
        "surface-dim":                  "#0f131c",
        "inverse-surface":              "#dfe2ef",
        "on-surface":                   "#dfe2ef",
        "tertiary-container":           "#7ac68b",
        "primary-fixed-dim":            "#30e375",
        "on-tertiary-container":        "#005327",
        "on-surface-variant":           "#bbcbb9",
        "on-primary":                   "#003917",
        "on-secondary-fixed":           "#00164d",
        "outline":                      "#859585",
        "on-primary-fixed":             "#00210b",
        "primary":                      "#42ee7f",
        "on-secondary":                 "#00287b",
        "on-background":                "#dfe2ef",
        "error-container":              "#93000a",
        "surface-bright":               "#353943",
        "outline-variant":              "#3c4a3d",
        "secondary-container":          "#024cd6",
        "primary-container":            "#00d166",
        "surface-container-high":       "#262a34",
        "background":                   "#0f131c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        sm:               "12px",
        base:             "8px",
        xl:               "80px",
        "margin-desktop": "64px",
        "margin-mobile":  "16px",
        lg:               "48px",
        xs:               "4px",
        md:               "24px",
        gutter:           "24px",
      },
      fontFamily: {
        "headline-md":  ["Hanken Grotesk"],
        "body-lg":      ["Inter"],
        "headline-sm":  ["Hanken Grotesk"],
        "label-caps":   ["JetBrains Mono"],
        "display-lg":   ["Hanken Grotesk"],
        "body-md":      ["Inter"],
        "system-data":  ["JetBrains Mono"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps":  ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "display-lg":  ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "system-data": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
};